# Generated by Django 5.2.17 on 2026-09-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionchat',
            options={'ordering': ['-favorito', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='sesionchat',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
