# Generated by Django 5.2.17 on 2026-09-22 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_alter_sesionchat_options_sesionchat_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_chat/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('ruta_markdown', models.CharField(blank=True, default='', max_length=512)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='a_rtchat.sesionchat')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
