# Generated by Django 5.2.17 on 2026-09-25 16:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_documentosesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Identificador único del producto', max_length=50, unique=True, verbose_name='Código (SKU)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del componente')),
                ('descripcion', models.TextField(verbose_name='Descripción técnica')),
                ('categoria', models.CharField(choices=[('Procesadores', 'Procesadores'), ('Placas Base', 'Placas Base'), ('Memoria RAM', 'Memoria RAM'), ('Tarjetas Gráficas', 'Tarjetas Gráficas'), ('Almacenamiento', 'Almacenamiento'), ('Fuentes de Poder', 'Fuentes de Poder'), ('Gabinetes/Chasis', 'Gabinetes/Chasis'), ('Refrigeración', 'Refrigeración'), ('Monitores', 'Monitores'), ('Teclados', 'Teclados'), ('Ratones', 'Ratones'), ('Audio', 'Audio'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, help_text='No se permiten valores negativos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio ($)')),
                ('cantidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad existente en stock')),
                ('stock_minimo', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo permitido')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Reacondicionado', 'Reacondicionado'), ('Usado', 'Usado')], default='Nuevo', max_length=20, verbose_name='Estado del producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para realizar eliminación lógica del producto', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
